import Navigation from "../components/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* layout 컴포넌트에서 전체적인 레이아웃을 잡는다. React 에서 app 이나 index 의 역할을 한다고 보면 된다. */}
        <Navigation />
        {children}
      </body>
    </html>
  )
}
